# Generated by Django 4.1.1 on 2022-09-23 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128)),
                ('life_span', models.CharField(blank=True, max_length=16, null=True)),
                ('description', models.TextField(blank=True, max_length=999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Zacheta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, max_length=999, null=True)),
                ('note_for_teacher', models.TextField(blank=True, max_length=999, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paintings.author')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paintings.tag')),
            ],
        ),
        migrations.CreateModel(
            name='OtherPaintings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, max_length=999, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paintings.author')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paintings.tag')),
                ('zacheta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paintings.zacheta')),
            ],
        ),
    ]
