# Generated by Django 4.1.1 on 2022-09-23 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paintings', '0003_remove_otherpaintings_tags_otherpaintings_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherpaintings',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='zacheta',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='otherpaintings',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Paintings.author'),
        ),
        migrations.AlterField(
            model_name='zacheta',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='Paintings.tag'),
        ),
    ]
