# Generated by Django 4.1.1 on 2022-09-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paintings', '0004_otherpaintings_title_zacheta_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otherpaintings',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zacheta',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
