# Generated by Django 4.1.1 on 2022-09-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paintings', '0005_alter_author_id_alter_otherpaintings_id_alter_tag_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='life_span',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
