# Generated by Django 4.1.1 on 2022-09-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paintings', '0006_alter_author_life_span'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherpaintings',
            name='url',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='zacheta',
            name='url',
            field=models.CharField(max_length=256),
        ),
    ]
