# Generated by Django 4.1.1 on 2022-09-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paintings', '0007_alter_otherpaintings_url_alter_zacheta_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
