# Generated by Django 4.1.1 on 2022-09-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paintings', '0008_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(max_length=512, primary_key=True, serialize=False),
        ),
    ]
