# Generated by Django 4.1.1 on 2022-09-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paintings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zacheta',
            name='tags',
        ),
        migrations.AddField(
            model_name='zacheta',
            name='tags',
            field=models.ManyToManyField(to='Paintings.tag'),
        ),
    ]
