# Generated by Django 4.1.1 on 2022-09-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paintings', '0002_remove_zacheta_tags_zacheta_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherpaintings',
            name='tags',
        ),
        migrations.AddField(
            model_name='otherpaintings',
            name='tags',
            field=models.ManyToManyField(to='Paintings.tag'),
        ),
    ]
