# Generated by Django 4.1.1 on 2022-09-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Paintings", "0003_remove_otherpaintings_tags_otherpaintings_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="otherpaintings",
            old_name="url",
            new_name="guid",
        ),
        migrations.AddField(
            model_name="otherpaintings",
            name="full",
            field=models.URLField(default="example.com/non-existing-full"),
        ),
        migrations.AddField(
            model_name="otherpaintings",
            name="preview",
            field=models.URLField(default="example.com/non-existing-preview"),
        ),
    ]
